#!/bin/bash -eu

function install_xkb {
  local self=$(readlink -f "${BASH_SOURCE[0]}")
  local dir=$(dirname $self)

  read -p "Install layouts onto XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-${HOME}/.config}? Y/n: " confirm
  local confirm=$(echo ${confirm} | tr [:lower:] [:upper:])
  if [[ "${confirm:-Y}" == "Y" ]] ;then
    echo "[Installing files onto ${XDG_CONFIG_HOME:-${HOME}/.config}]"
    mkdir -p ${HOME}/.config/xkb
    cp -rpv ${dir}/xkb/{symbols,rules} ${XDG_CONFIG_HOME:-${HOME}/.config}/xkb
  fi
  
  read -p "Install layouts onto /usr/share/X11/xkb? Y/n: " confirm
  local confirm=$(echo ${confirm} | tr [:lower:] [:upper:])
  if [[ "${confirm:-Y}" == "Y" ]] ;then
    echo "[Installing hyena onto /usr/share/X11/xkb]"
    sudo cp -rpv ${dir}/xkb/symbols/custom /usr/share/X11/xkb/symbols
  else
    if [[ -f /usr/share/X11/xkb/symbols/hyena ]] ;then
      echo "[Removing hyena from /usr/share/X11/xkb/symbols]"
      sudo rm /usr/share/X11/xkb/symbols/{custom}
    fi
  fi
  
  read -p "Add aliases hyena- (Standard US layout) and hyena+ (Standard US Layout + Hyena) into your ${HOME}/.bashrc? Y/n: " confirm
  local confirm=$(echo ${confirm} | tr [:lower:] [:upper:])
  if [[ "${confirm:-Y}" == "Y" ]] ;then
      cat <<EOD | tee -a ${HOME}/.bashrc
alias US='setxkbmap -layout "us" -variant "symbolic" -print | xkbcomp -a - $DISPLAY'
alias hyena='setxkbmap -layout "us,custom" -variant "symbolic,hyena" -option altwin:meta_alt,ctrl:swap_lalt_lctl,lv3:switch,lv5:ralt_switch,grp:caps_switch -print | xkbcomp -a - $DISPLAY'
alias miniguru='setxkbmap -layout "us,custom" -variant "symbolic,miniguru" -option altwin:meta_alt,ctrl:swap_lalt_lctl,lv3:switch,lv5:ralt_switch,grp:caps_switch -print | xkbcomp -a - $DISPLAY'
alias yoda='setxkbmap -layout "us,custom" -variant "symbolic,yoda" -option altwin:meta_alt,ctrl:swap_lalt_lctl,lv3:switch,lv5:ralt_switch,grp:caps_switch -print | xkbcomp -a - $DISPLAY'

# Activate Hyena layout
# hyena
EOD
  fi
}    

if [ $_ != $0 ] ;then
  # echo "Script is being sourced: list all functions"
  self=$(readlink -f "${BASH_SOURCE[0]}"); dir=$(dirname $self)
  grep -E "^function " $self | fgrep -v "function __" | cut -d' ' -f2 | head -n -1
else
  # echo "Script is a subshell: execute last function"
  self=$(readlink -f "${BASH_SOURCE[0]}"); dir=$(dirname $self)
  cmd=$(grep -E "^function " $self | cut -d' ' -f2 | tail -1)
  $cmd $*
fi
