#!/bin/bash -eu

function install_xkb {
  local self=$(readlink -f "${BASH_SOURCE[0]}")
  local dir=$(dirname $self)

  read -p "Install layouts onto XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-${HOME}/.config}? Y/n: " confirm
  local confirm=$(echo ${confirm} | tr [:lower:] [:upper:])
  if [[ "${confirm:-Y}" == "Y" ]] ;then
    echo "[Installing files onto ${XDG_CONFIG_HOME:-${HOME}/.config}]"
    mkdir -p ${HOME}/.config/xkb
    cp -rpv ${dir}/xkb/symbols ${XDG_CONFIG_HOME:-${HOME}/.config}/xkb
    cp -rpv ${dir}/xkb/rules   ${XDG_CONFIG_HOME:-${HOME}/.config}/xkb
  fi
  
  read -p "Install layouts onto /usr/share/X11/xkb? y/N: " confirm
  local confirm=$(echo ${confirm} | tr [:lower:] [:upper:])
  if [[ "${confirm:-N}" == "Y" ]] ;then
    echo "[Installing files onto /usr/share/X11/xkb]"
    mkdir -p ${HOME}/.config/xkb
    sudo cp -rpv ${dir}/xkb/symbols/hyena /usr/share/X11/xkb/symbols
  fi
  
  echo '-------------------------------------------------------------------------------------------------------'
  echo 'Hyena installed. You can try the command below:'
  echo '    setxkbmap -layout "us,hyena" \'
  echo '              -variant "symbolic,level1" \'
  echo '              -option altwin:meta_alt,ctrl:swap_lalt_lctl,lvl3:switch,grp:caps_switch,grp:menu_switch \'
  echo '              -print | xkbcomp -a - $DISPLAY'
  echo '-------------------------------------------------------------------------------------------------------'
}    

if [ $_ != $0 ] ;then
  # echo "Script is being sourced: list all functions"
  self=$(readlink -f "${BASH_SOURCE[0]}"); dir=$(dirname $self)
  grep -E "^function " $self | fgrep -v "function __" | cut -d' ' -f2 | head -n -1
else
  # echo "Script is a subshell: execute last function"
  self=$(readlink -f "${BASH_SOURCE[0]}"); dir=$(dirname $self)
  cmd=$(grep -E "^function " $self | cut -d' ' -f2 | tail -1)
  $cmd $*
fi
